export const siteConfig = {
  name: "Virelio",
  description: "AI Agents & Automatisering voor bedrijven",
  url: "https://virelio.nl",
  metadataBase: "https://virelio.nl",
  logoUrl: "/logo.svg",
  ogImage: "/og-image.jpg",
  twitterHandle: "@robinbril",
  locale: "nl",
  authors: [
    {
      name: "Robin Bril",
      url: "https://virelio.nl",
    },
  ],
  socials: {
    twitter: "https://twitter.com/robinbril",
    github: "https://github.com/robinbril",
    linkedin: "https://linkedin.com/in/robinbril",
  },
  contact: {
    email: "robin@virelio.nl",
    phone: "+31 (0)6 40446732",
    address: "Amstelveen, Netherlands",
  },
  themeColor: "#ffffff",
  keywords: [
    "AI Agents",
    "AI Automatisering",
    "RAG Systemen",
    "Procesautomatisering",
    "AI Engineer",
    "Robin Bril",
    "Virelio",
    "AI Kennisbank",
    "Document Intelligence",
    "AI Oplossingen Nederland",
    "Amstelveen AI",
    "LangChain",
    "AI Consultancy",
  ],
  alternateLanguages: {
    nl: "https://virelio.nl",
    en: "https://virelio.nl/en",
  },
  sections: {
    projects: "#projects",
    services: "#services",
    workshop: "#workshop",
    about: "#about",
    testimonials: "#testimonials",
    demo: "#demo",
    bookMeeting: "#book-meeting",
    contact: "#contact",
    home: "#",
  },
};
